#!/bin/bash
set -e

# Create config directory
mkdir -p /etc/flux-spooler
chmod 755 /etc/flux-spooler

# Create systemd user for the service if it doesn't exist
if ! id "flux-spooler" &>/dev/null; then
    useradd --system --home /var/lib/flux-spooler --shell /bin/false flux-spooler
fi

# Create home directory
mkdir -p /var/lib/flux-spooler
chown flux-spooler:flux-spooler /var/lib/flux-spooler
chmod 750 /var/lib/flux-spooler

#DEBHELPER#

exit 0